// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Delayed from "./delayed_controller"
import HideController from "./hide_controller"
import PermanentController from "./permanent_controller"
import ShowController from "./show_controller"
application.register("delayed", Delayed)
application.register("hide", HideController)
application.register("permanent", PermanentController)
application.register("show", ShowController)
